- CHANGELOG.md
- dist/bump/index.js
- src/actions/bump.ts
Paginating like the original implementation doesn't go down well on a large repository; we only fetch 100 parents now.
Also, add some debug logging before the Octokit calls.
> fix(bump): don't fetch the complete repo

- README.md
- bump/action.yml
This input's default was documented incorrectly.
> docs(bump): fix incorrect `create-release` documentation

- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- src/config.ts
- src/interfaces.ts
- src/rules.ts
- test/commit.test.ts
The `disable` keyword in the Configuration file was not applied correctly when executing the ruleset for Conventional Commit-message checking.
Fixes: #114
> fix: apply `disable`-configuration parameter

- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- src/rules.ts
- test/rules.test.ts
The check was intended to work this way as can be seen from the way the error message is created (it references the first word).
> fix(imperative-mood-rule): check only first word of description

- README.md
- action.yml
- dist/bump/index.js
- dist/validate/index.js
- src/actions/validate.ts
- src/github.ts
- src/validate.ts
This introduces a new check which ensures the pull request title
represents the same bump level as the highest bump level in the
list of commits associated with that pull request.
The check can be disabled by setting `validate-pull-request-title-bump`
action input to `false`.
> feat: add PR title bump level validation

- README.md
- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- src/actions/bump.ts
- src/bump.ts
- src/changelog.ts
- src/config.ts
- src/interfaces.ts
- src/semver.ts
- test/changelog.test.ts
- test/config.test.ts
- test/semver.test.ts
During initial development, you should avoid bumping the `MAJOR` version. By default, we will bump the `MINOR` version for breaking changes in case:
- The current `MAJOR`-version is `0`
- **AND** the `initial-development` configuration parameter is `true` (default value)
We will automatically bump the version to `1.0.0` when:
- The current `MAJOR`-version is `0`
- **AND** the `initial-development` configuration parameter is `false`
> NOTE: This behavior also applies to non-bumping commits (ie. `chore:`, `ci:`)
> feat: add support for Initial Development

- dist/bump/index.js
- dist/validate/index.js
- src/actions/bump.ts
- src/bump.ts
- src/github.ts
- src/interfaces.ts
The REST API call used previously is both not properly documented and did not behave as assumed, leading to failure to resolve the latest tags if the version scheme changed and the total amount of tags in the repo exceeds 100.
We now order explicitly by GitHub's own `TAG_COMMIT_DATE`, which introduces another caveat; the documentation for that order method says:
> Order refs by underlying commit date if the ref prefix is refs/tags/
No mention of how that is implemented or what Git data it uses under the hood. The phrasing _hints_ that it uses the ref's `committerdate`, which would be invalid for annotated tags, but during testing, it appears to "work fine", which means it probably uses `creatordate` or (more likely) a custom implementation.
> fix(bump): use  GitHub API for fetching tags by date

- .github/workflows/quality-checks.yml
- README.md
- dist/bump/index.js
- dist/validate/index.js
- src/actions/bump.ts
- src/actions/validate.ts
- src/bump.ts
- src/commit.ts
- src/github.ts
- src/validate.ts
This feature will add a label (`bump:{version}`) to your Pull Request, based on the valid Conventional Commit messages present in your Pull Request (i.e. `bump:minor`).
This label can be used to either:
- Review whether the right SemVer version will be bumped
- Used by automation (i.e. automatic Release Notes generation)
**NOTE**: This feature requires `write` permissions for both `issues` and `pull-requests` for the used GitHub token.
> feat: add SemVer labels to the Pull Request

- README.md
- dist/bump/index.js
- src/changelog.ts
- test/changelog.test.ts
This Pull Request will allow users to group their Changelog file based on the Conventional Commit scope, i.e.:
* Added `doIt(...)` interface to do it [[17e57c]()]
* Extended `doIt(...)` to allow for deferred actions [[17e57c]()]
* Updated Search API documentation [[27e57c]()]
* Very important fix for development tooling [[17e57c]()]
> feat: support grouping changelog entries by scope

- dist/bump/index.js
- dist/validate/index.js
- src/bump.ts
- src/github.ts
To avoid getting an ever-growing list of draft-releases, instead of
checking only the next minor and next major versions for draft release
updates, check every draft release matching our version prefix.
In other words, we just re-use the one draft release every time, until
it turns into an RC or release.
> chore: consider all draft releases for updates

- dist/bump/index.js
- dist/validate/index.js
- src/bump.ts
Re-using a draft release from a release branch will reset the `dev-N` numbering, so let's only re-use draft releases from non-release branches.
> fix(sdkver): don't re-use draft releases on release branches

- dist/bump/index.js
- dist/validate/index.js
- src/bump.ts
- test/bump.sdkver.test.ts
Currently, a new major range is started on `-dev` releases when breaking changes are present in the history list.
This is not always desirable, so this removes that behavior for now.
> fix: do not bump dev releases with breaking changes

- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- src/bump.ts
- src/semver.ts
- test/bump.sdkver.test.ts
When a build is re-run on a release branch while nothing has changed, that is, while HEAD still matches the latest tag, we now no longer blindly bump another RC version on top of it.
This flow is more common than one might assume, since GitHub workflows push triggers trigger on ref pushes of "empty branches", as well.
> fix(sdkver): avoid double bump on release branches

- dist/bump/index.js
- dist/validate/index.js
- src/bump.ts
- src/changelog.ts
- src/github.ts
- src/interfaces.ts
- test/bump.sdkver.test.ts
- test/changelog.test.ts
Instead of the "current version", which may be an `-rc` or `-dev` version,
we now always get the list of commits since the last full release and
base our changelog on that.
A "full release" is any release without a prerelease marker (`-`).
Changelog generation has seen some refactoring to accommodate that,
as the described flow requires different/customizable source data.
> improvement(sdkver): make changelog relative to last full release

- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- docs/configuration.md
- docs/sdk-versioning.md
- src/bump.ts
- src/config.ts
- src/github.ts
- test/bump.sdkver.test.ts
- test/config.test.ts
Whenever an RC- or release-build is run on a non-release branch, we can now automatically push a release branch ref to the repo. The functionality, which is _disabled_ by default, can be enabled with a configuration option:
```yaml
sdkver-create-release-branches: true
```
> feat(sdkver): add option to automatically create release branch

- bump/action.yml
- dist/bump/index.js
- dist/validate/index.js
- src/actions/bump.ts
- src/bump.ts
- test/bump.sdkver.test.ts
- test/bump.test.ts
- test/test_utils.ts
I need to be able to suppress the default commisery changelog, as in some cases I use another tool to generate the release notes in a different format.
The current way is a bit crude, but maybe it's good enough.
> feat(bump): skip creation of changelog when requested

- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- docs/sdk-versioning.md
- src/bump.ts
- src/semver.ts
- test/bump.sdkver.test.ts
- test/semver.test.ts
This solves two issues in SdkVer:
- Since Maven/Gradle has issues with the build info `+` in the version
string, move the commit hash information the prerelease field.
- Dev- and RC-releases are interpreted lexically, so zero-pad them to
avoid e.g.: `0.1.2-dev9 > 0.1.2-dev10`
Dev releases are padded to THREE characters, while RC releases are
padded to TWO characters.
> fix: use prerelease field for dev commit hash and zero-pad numbers

- package.json
The `**` glob pattern will recursively list all subfolders.
> chore: no longer execute prettier twice over all files

- .github/workflows/quality-checks.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- action.yml
- bump/action.yml
- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- package-lock.json
- package.json
- tsconfig.json
As taken from the GitHub Blog:
> Node 16 has reached its end of life, prompting us to initiate
> its deprecation process for GitHub Actions. Our plan is to
> transition all actions to run on Node 20 by Spring 2024.
This Pull Request:
- updates the minimum supported version of `commisery-action` to Node20.
- updates the used GitHub Actions to the latest version (supporting Node20)
see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
thanks-to: @brunorosa-tomtom
> feat!: upgrade minimum node version to v20

- dist/bump/index.js
- dist/validate/index.js
- src/bump.ts
- src/github.ts
- test/bump.sdkver.test.ts
- test/bump.test.ts
We used to fetch only the 100 latest tags; that is not sufficient in a repository with heavy traffic, especially when an older release requires a fix up.
The way we currently determine the last matching tags unfortunately requires us to fetch either all commits or all tags in a repository and match them to each other.
(Tags is the more obvious choice, as they are bound to be less numerous than commits.)
> fix(bump): paginate and get all tags while determining bump

- README.md
- dist/bump/index.js
- dist/validate/index.js
- src/actions/validate.ts
- src/github.ts
- test/validate.test.ts
Continuation of effort start in: https://github.com/tomtom-international/commisery-action/pull/281
> feat: commisery-action support runs triggered by merge_group event

- .github/workflows/check-dist.yml
The branch protection rules require check-dist to be completed before merging is allowed - this filter is preventing the workflow to be executed in case we only change a readme file.
> ci: remove path-filters from check-dist

- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- src/config.ts
The `release-branches` configuration parameter was passed as `string` instead of the expected `RegExp` type.
> fix: convert release-branches regex to RegExp object

- dist/bump/index.js
- dist/cli/index.js
- dist/validate/index.js
- docs/configuration.md
- src/bump.ts
- src/config.ts
- src/github.ts
- test/bump.sdkver.test.ts
- test/bump.test.ts
This allows to enable to create a discussion from a GitHub release. See: https://github.blog/changelog/2021-04-06-releases-support-comments-and-reactions-with-discussion-linking/
> feat: add github release discussion category configuration option

- dist/bump/index.js
- dist/validate/index.js
- src/bump.ts
- test/bump.sdkver.test.ts
- test/bump.test.ts
This change will correctly handle our commisery outputs in case `create-tag` and `create-release` are both set to `false`. This is handled by returning the VersionInformation in case we either have a successful publication (`bump === true`) _or_ we do not need to publish (`releaseMode === "none"`).
> fix: set outputs in case of no tag and release publication
